bedtools	sort	-i	0_roadmap/roadmap_001_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_001_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_002_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_002_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_003_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_003_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_004_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_004_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_005_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_005_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_006_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_006_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_007_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_007_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_008_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_008_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_009_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_009_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_010_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_010_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_011_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_011_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_012_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_012_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_013_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_013_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_014_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_014_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_015_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_015_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_016_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_016_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_017_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_017_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_018_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_018_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_019_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_019_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_020_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_020_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_021_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_021_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_022_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_022_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_023_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_023_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_024_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_024_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_025_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_025_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_026_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_026_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_027_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_027_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_028_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_028_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_029_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_029_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_030_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_030_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_031_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_031_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_032_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_032_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_033_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_033_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_034_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_034_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_035_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_035_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_036_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_036_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_037_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_037_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_038_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_038_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_039_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_039_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_040_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_040_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_041_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_041_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_042_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_042_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_043_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_043_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_044_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_044_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_045_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_045_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_046_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_046_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_047_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_047_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_048_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_048_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_049_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_049_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_050_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_050_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_051_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_051_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_052_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_052_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_053_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_053_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_054_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_054_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_055_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_055_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_056_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_056_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_057_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_057_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_058_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_058_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_059_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_059_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_061_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_061_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_062_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_062_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_063_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_063_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_065_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_065_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_066_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_066_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_067_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_067_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_068_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_068_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_069_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_069_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_070_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_070_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_071_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_071_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_072_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_072_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_073_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_073_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_074_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_074_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_075_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_075_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_076_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_076_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_077_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_077_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_078_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_078_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_079_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_079_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_080_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_080_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_081_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_081_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_082_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_082_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_083_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_083_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_084_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_084_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_085_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_085_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_086_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_086_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_087_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_087_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_088_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_088_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_089_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_089_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_090_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_090_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_091_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_091_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_092_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_092_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_093_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_093_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_094_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_094_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_095_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_095_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_096_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_096_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_097_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_097_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_098_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_098_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_099_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_099_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_100_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_100_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_101_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_101_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_102_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_102_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_103_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_103_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_104_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_104_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_105_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_105_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_106_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_106_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_107_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_107_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_108_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_108_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_109_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_109_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_110_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_110_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_111_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_111_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_112_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_112_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_113_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_113_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_114_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_114_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_115_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_115_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_116_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_116_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_117_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_117_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_118_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_118_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_119_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_119_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_120_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_120_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_121_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_121_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_122_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_122_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_123_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_123_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_124_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_124_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_125_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_125_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_126_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_126_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_127_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_127_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_128_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_128_enh.tsv
bedtools	sort	-i	0_roadmap/roadmap_129_enh.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	0_roadmap_dist_37/roadmap_129_enh.tsv