bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Bulk_B.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Bulk_B.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Bulk_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Bulk_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Central_memory_CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Central_memory_CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Central_memory_CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Central_memory_CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Effector_CD4pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Effector_CD4pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Effector_CD4pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Effector_CD4pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Effector_memory_CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Effector_memory_CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Effector_memory_CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Effector_memory_CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Follicular_T_Helper.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Follicular_T_Helper.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Follicular_T_Helper.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Follicular_T_Helper.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Gamma_delta_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Gamma_delta_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Immature_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Immature_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Mature_NK.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Mature_NK.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Mature_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Mature_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Mem_B.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Mem_B.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Mem_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Mem_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Memory_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Memory_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Memory_Teffs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Memory_Teffs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Memory_Teffs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Memory_Teffs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Memory_Tregs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Memory_Tregs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Memory_Tregs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Memory_Tregs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Monocytes.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Monocytes.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Monocytes.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Monocytes.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Myeloid_DCs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Myeloid_DCs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Naive_B.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Naive_B.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Naive_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Naive_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Naive_CD8_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Naive_CD8_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Naive_CD8_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Naive_CD8_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Naive_Teffs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Naive_Teffs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Naive_Teffs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Naive_Teffs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Plasmablasts.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Plasmablasts.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Regulatory_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Regulatory_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Regulatory_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Regulatory_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Th17_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Th17_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Th17_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Th17_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Th1_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Th1_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Th1_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Th1_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Th2_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Th2_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.Th2_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.Th2_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1001.pDCs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1001.pDCs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Bulk_B.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Bulk_B.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Bulk_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Bulk_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Central_memory_CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Central_memory_CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Central_memory_CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Central_memory_CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Effector_CD4pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Effector_CD4pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Effector_CD4pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Effector_CD4pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Effector_memory_CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Effector_memory_CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Effector_memory_CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Effector_memory_CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Follicular_T_Helper.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Follicular_T_Helper.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Follicular_T_Helper.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Follicular_T_Helper.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Gamma_delta_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Gamma_delta_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Gamma_delta_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Gamma_delta_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Immature_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Immature_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Mature_NK.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Mature_NK.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Mem_B.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Mem_B.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Mem_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Mem_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Memory_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Memory_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Memory_Teffs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Memory_Teffs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Memory_Teffs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Memory_Teffs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Memory_Tregs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Memory_Tregs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Memory_Tregs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Memory_Tregs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Monocytes.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Monocytes.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Myeloid_DCs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Myeloid_DCs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Naive_B.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Naive_B.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Naive_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Naive_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Naive_CD8_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Naive_CD8_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Naive_CD8_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Naive_CD8_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Naive_Teffs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Naive_Teffs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Naive_Teffs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Naive_Teffs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Plasmablasts.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Plasmablasts.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Regulatory_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Regulatory_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Regulatory_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Regulatory_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Th17_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Th17_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Th17_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Th17_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Th1_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Th1_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Th1_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Th1_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Th2_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Th2_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.Th2_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.Th2_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1002.pDCs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1002.pDCs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Bulk_B.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Bulk_B.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Bulk_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Bulk_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Central_memory_CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Central_memory_CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Central_memory_CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Central_memory_CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Effector_CD4pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Effector_CD4pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Effector_CD4pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Effector_CD4pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Effector_memory_CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Effector_memory_CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Effector_memory_CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Effector_memory_CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Follicular_T_Helper.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Follicular_T_Helper.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Follicular_T_Helper.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Follicular_T_Helper.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Gamma_delta_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Gamma_delta_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Gamma_delta_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Gamma_delta_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Immature_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Immature_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Mature_NK.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Mature_NK.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Mature_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Mature_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Mem_B.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Mem_B.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Mem_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Mem_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Memory_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Memory_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Memory_Teffs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Memory_Teffs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Memory_Teffs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Memory_Teffs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Memory_Tregs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Memory_Tregs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Memory_Tregs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Memory_Tregs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Monocytes.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Monocytes.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Monocytes.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Monocytes.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Naive_B.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Naive_B.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Naive_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Naive_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Naive_CD8_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Naive_CD8_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Naive_CD8_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Naive_CD8_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Naive_Teffs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Naive_Teffs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Naive_Teffs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Naive_Teffs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Regulatory_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Regulatory_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Regulatory_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Regulatory_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Th17_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Th17_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Th1_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Th1_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Th1_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Th1_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Th2_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Th2_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1003.Th2_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1003.Th2_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Bulk_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Bulk_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Central_memory_CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Central_memory_CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Central_memory_CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Central_memory_CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Effector_CD4pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Effector_CD4pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Effector_memory_CD8pos_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Effector_memory_CD8pos_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Effector_memory_CD8pos_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Effector_memory_CD8pos_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Follicular_T_Helper.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Follicular_T_Helper.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Follicular_T_Helper.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Follicular_T_Helper.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Gamma_delta_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Gamma_delta_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Gamma_delta_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Gamma_delta_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Immature_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Immature_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Mature_NK.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Mature_NK.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Mature_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Mature_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Mem_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Mem_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Memory_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Memory_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Memory_Teffs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Memory_Teffs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Memory_Teffs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Memory_Teffs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Memory_Tregs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Memory_Tregs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Memory_Tregs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Memory_Tregs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Monocytes.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Monocytes.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Monocytes.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Monocytes.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Naive_B.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Naive_B.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Naive_CD8_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Naive_CD8_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Naive_CD8_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Naive_CD8_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Naive_Teffs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Naive_Teffs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Naive_Teffs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Naive_Teffs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Naive_Tregs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Naive_Tregs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Naive_Tregs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Naive_Tregs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Regulatory_T.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Regulatory_T.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Regulatory_T.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Regulatory_T.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Th17_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Th17_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Th17_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Th17_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Th1_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Th1_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Th1_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Th1_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Th2_precursors.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Th2_precursors.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1004.Th2_precursors.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1004.Th2_precursors.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1008.Immature_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1008.Immature_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1008.Mature_NK.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1008.Mature_NK.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1008.Mature_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1008.Mature_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1008.Memory_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1008.Memory_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1008.Monocytes.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1008.Monocytes.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1008.Myeloid_DCs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1008.Myeloid_DCs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1008.Naive_Tregs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1008.Naive_Tregs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1008.pDCs.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1008.pDCs.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1010.Follicular_T_Helper.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1010.Follicular_T_Helper.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1010.Mature_NK.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1010.Mature_NK.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1010.Mem_B.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1010.Mem_B.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1010.Memory_NK.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1010.Memory_NK.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1010.Monocytes.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1010.Monocytes.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1010.Naive_Tregs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1010.Naive_Tregs.S.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1010.Plasmablasts.U.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1010.Plasmablasts.U.tsv
bedtools	sort	-i	./2_pritchardlab/Pritchard_X1011.Naive_Teffs.S.bed	|	bedtools	closest	-d	-a	gwas_hg19_biomart_37.bed	-b	stdin	>	./2_pritchardlab_dist_37/1011.Naive_Teffs.S.tsv
